// Code generated by cli-generator; DO NOT EDIT.
package cmd



import (
	
	handler "github.com/codefresh-io/step-generator/pkg/decompose"
	
	"github.com/spf13/cobra"
)

var decomposeCmdOptions struct {
	file string
	
}

var decomposeCmd = &cobra.Command{
	Use:     "decompose",

	RunE: func(cmd *cobra.Command, args []string) error {
		h := &handler.Handler{}
		return h.Handle(cnf)
	},
	Long: "Quickly generate Codefresh step-types",
	PreRun: func(cmd *cobra.Command, args []string) {
		rootCmd.PreRun(cmd, args)
		
		cnf.Set("file", decomposeCmdOptions.file)
		
	},
}




func init() {

	
	decomposeCmd.PersistentFlags().StringVar(&decomposeCmdOptions.file, "file", cnf.GetString("file"), "Path to file of step-type.yaml")
	rootCmd.AddCommand(decomposeCmd)
}